from django.db import models
from api.fields import JSONField

# Create your models here.
# You get a database table
class Campaign(models.Model):
    url = models.TextField(null=True, blank=True)
    campaign_id = models.TextField(null=True, blank=True)
    auto_fb_post_mode = models.TextField(null=True, blank=True)
    collected_date = models.TextField(null=True, blank=True)
    category_id = models.TextField(null=True, blank=True)
    category = models.TextField(null=True, blank=True)
    currencycode = models.TextField(null=True, blank=True)
    current_amount = models.TextField(null=True, blank=True)
    goal = models.TextField(null=True, blank=True)
    donators = models.TextField(null=True, blank=True)
    days_active = models.TextField(null=True, blank=True)
    days_created = models.TextField(null=True, blank=True)
    title = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    default_url = models.TextField(null=True, blank=True)
    has_beneficiary = models.TextField(null=True, blank=True)
    media_type = models.TextField(null=True, blank=True)
    project_type = models.TextField(null=True, blank=True)
    turn_off_donations = models.TextField(null=True, blank=True)
    user_id = models.TextField(null=True, blank=True)
    user_first_name = models.TextField(null=True, blank=True)
    user_last_name = models.TextField(null=True, blank=True)
    user_facebook_id = models.TextField(null=True, blank=True)
    user_profile_url = models.TextField(null=True, blank=True)
    visible_in_search = models.TextField(null=True, blank=True)
    status = models.TextField(null=True, blank=True)
    deactivated = models.TextField(null=True, blank=True)
    state = models.TextField(null=True, blank=True)
    is_launched = models.TextField(null=True, blank=True)
    campaign_image_url = models.TextField(null=True, blank=True)
    created_at = models.TextField(null=True, blank=True)
    launch_date = models.TextField(null=True, blank=True)
    campaign_hearts = models.TextField(null=True, blank=True)
    social_share_total = models.TextField(null=True, blank=True)
    social_share_last_update = models.TextField(null=True, blank=True)
    location_city = models.TextField(null=True, blank=True)
    location_country = models.TextField(null=True, blank=True)
    location_zip = models.TextField(null=True, blank=True)
    is_charity = models.TextField(null=True, blank=True)
    charity_valid = models.TextField(null=True, blank=True)
    charity_npo_id = models.TextField(null=True, blank=True)
    charity_name = models.TextField(null=True, blank=True)
    velocity = models.TextField(null=True, blank=True)

#class Donation(models.Model):
#    donation_id = models.TextField(null=True, blank=True)
#    campaign_id = models.ForeignKey(Campaign, on_delete=models.PROTECT)
#    collected_date = models.TextField(null=True, blank=True)
#    amount = models.TextField(null=True, blank=True)
#    is_offline = models.TextField(null=True, blank=True)
#    is_anonymous = models.TextField(null=True, blank=True)
#    name = models.TextField(null=True, blank=True)
#    created_at = models.TextField(null=True, blank=True)
#    profile_url = models.TextField(null=True, blank=True)
#    verified = models.TextField(null=True, blank=True)
#    
#class Update(models.Model):
#    update_id = models.TextField(null=True, blank=True)
#    campaign_id = models.ForeignKey(Campaign, on_delete=models.PROTECT)
#    collected_date = models.TextField(null=True, blank=True)
#    photo_url = models.TextField(null=True, blank=True)
#    created_at = models.TextField(null=True, blank=True)
#    updates_author = models.TextField(null=True, blank=True)
#    updates_author_type = models.TextField(null=True, blank=True)
#    updates_text = models.TextField(null=True, blank=True)
#    comments = models.TextField(null=True, blank=True)
#    